version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: sh -c "ls -la /usr/src/app && bash /usr/src/app/entrypoint.sh && gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.dev

volumes:
  postgres_data: